files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - js/**/*.js
  # define files excluded from the analysis (defaults to [])
  excluded:
    - assets/**/*.css
    - /**/*.html